# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(750, 671)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Adobe Express - file (14).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 761, 61))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(20, 89, 114);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(610, 17, 130, 38))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/newPrefix/Screenshot 2023-11-30 195942 (1).png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(494, 23, 103, 27))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/newPrefix/Danantara_Indonesia_(no_SW).svg.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(20, 530, 411, 80))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgb(41, 170, 177), stop:1 #00AFE3);\n"
"border-radius: 10px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(180, 14, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(200, 44, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 43, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(10, 70, 730, 441))
        self.frame_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius: 6px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(460, 620, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    /* Background Gradasi Cyan ke Biru PLN */\n"
"    background-color: #00A6D6;\n"
"    color: white;              /* Teks putih */\n"
"    font-family: \"Roboto\", \"Segoe UI\";\n"
"    font-weight: bold;         /* Teks tebal */\n"
"    font-size: 18px;\n"
"    border: none;              /* Hapus border default */\n"
"    border-radius: 8px;        /* Sudut melengkung halus */\n"
"    padding: 10px 20px;        /* Memberi ruang di dalam tombol */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Saat mouse diarahkan: Sedikit lebih terang/bersinar */\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #75E6FF, stop:1 #33C9F0);\n"
"    margin-top: -2px;          /* Efek tombol naik sedikit */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Saat ditekan: Warna solid biru tua */\n"
"    background-color: #008CB8;\n"
"    margin-top: 2px;           /* Efek tombol turun */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 620, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    /* Background Abu-abu Muda (Sesuai gambar) */\n"
"    background-color: #EEEEEE; \n"
"    \n"
"    /* Warna Teks Abu-abu Gelap */\n"
"    color: #777777;            \n"
"    \n"
"    /* Font Setting (Tetap sama dengan base) */\n"
"    font-family: \"Roboto\", \"Segoe UI\";\n"
"    font-weight: bold;         \n"
"    font-size: 18px;\n"
"    \n"
"    /* Structure */\n"
"    border: none;              \n"
"    border-radius: 8px; /* Jika ingin bulat seperti kapsul persis gambar, ganti jadi 25px */\n"
"    padding: 10px 20px;        \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Saat di-hover: Sedikit lebih gelap agar terlihat aktif */\n"
"    background-color: #E0E0E0; \n"
"    color: #555555; /* Teks jadi sedikit lebih hitam */\n"
"    \n"
"    margin-top: -2px; /* Efek tombol naik */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Saat ditekan: Abu-abu lebih gelap */\n"
"    background-color: #D6D6D6; \n"
"    \n"
"    margin-top: 2px;  /* Efek tombol turun */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(450, 530, 281, 80))
        self.frame_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x1:1, y1:1, stop:0 rgb(41, 170, 177), stop:1 #00AFE3);\n"
"border-radius: 10px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.temp_label = QtWidgets.QLabel(self.frame_4)
        self.temp_label.setGeometry(QtCore.QRect(20, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.temp_label.setFont(font)
        self.temp_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;")
        self.temp_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.temp_label.setObjectName("temp_label")
        self.hum_label = QtWidgets.QLabel(self.frame_4)
        self.hum_label.setGeometry(QtCore.QRect(20, 40, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.hum_label.setFont(font)
        self.hum_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;")
        self.hum_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.hum_label.setObjectName("hum_label")
        self.temp = QtWidgets.QLabel(self.frame_4)
        self.temp.setGeometry(QtCore.QRect(160, 14, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.temp.setFont(font)
        self.temp.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temp.setObjectName("temp")
        self.hum = QtWidgets.QLabel(self.frame_4)
        self.hum.setGeometry(QtCore.QRect(150, 43, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.hum.setFont(font)
        self.hum.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;")
        self.hum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hum.setObjectName("hum")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(360, 620, 103, 41))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/newPrefix/Untitled (3).png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_16.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.frame_4.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "ENTRY DATA"))
        self.label.setText(_translate("Dialog", "Location:"))
        self.label_4.setText(_translate("Dialog", "Ruang Breaker"))
        self.label_5.setText(_translate("Dialog", "20/12/2026 - 09:20"))
        self.label_3.setText(_translate("Dialog", "Time:"))
        self.pushButton.setText(_translate("Dialog", "Confirm"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.temp_label.setText(_translate("Dialog", "Temp:"))
        self.hum_label.setText(_translate("Dialog", "Humidity:"))
        self.temp.setText(_translate("Dialog", "25.5 °C"))
        self.hum.setText(_translate("Dialog", "76 %"))
import plnip_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
